CI: Submit the Application Payload to Microsoft store into CI
endlessm/kolibri-app pull request #55
Opened 2022-06-06 05:05 UTC by starnight

Bring the actions to submit Endless Key to Microsoft store
automatically when release.

https://phabricator.endlessm.com/T33436

2022-06-06 08:04 UTC, danigm approved these changes
Looks good to me

2022-06-06 20:04 UTC, jprvita requested changes

2022-06-06 20:04 UTC, jprvita commented on .github/workflows/main.yml
> +            -Verbose
I think we should add `-UpdateListings` here to also update the screenshots -- rationale in https://phabricator.endlessm.com/T33436#940050

2022-06-07 06:11 UTC, starnight commented on .github/workflows/main.yml
> +            -Verbose
Updated & place some discussion in https://phabricator.endlessm.com/T33436#940115

2022-06-07 21:24 UTC, jprvita commented on .github/workflows/main.yml
> +            -Verbose
Further discussion on the ticket.

2022-06-07 21:25 UTC, jprvita requested changes
Further discussion on https://phabricator.endlessm.com/T33436#940316

2022-06-08 07:49 UTC, starnight commented on .github/workflows/main.yml
> +            -Verbose
Updated!

2022-06-08 19:29 UTC, jprvita approved these changes

2022-06-08 19:30 UTC, merged